Feature/api
krav-ets/db-project pull request #14
Opened 2023-04-21 14:59 UTC by krav-ets

2023-04-24 15:15 UTC, greybutton requested changes
> [Merge branch 'develop' into feature/api](https://github.com/krav-ets/db-project/pull/14/commits/b151e6d94070e87e26450403f019a857eff2cc73)

таких коммитов быть не должно, если нужен код из девелопа в фича ветке, надо делать ребейс фича ветки от девелопа

2023-04-24 15:15 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +  respond_to :json
это можно в Api::V1::ApplicationController перенести, чтобы в каждой контроллере не повторять

2023-04-24 15:15 UTC, greybutton commented on app/models/task.rb
> +  def self.ransackable_attributes(_auth_object = nil)
это зачем?

2023-04-24 19:04 UTC, krav-ets commented on app/models/task.rb
> +  def self.ransackable_attributes(_auth_object = nil)
если без этого, то во время тестов выпадает ошибка:

> Error:
Api::V1::TasksControllerTest#test_should_get_index:
RuntimeError: Ransack needs Task attributes explicitly allowlisted as
searchable. Define a `ransackable_attributes` class method in your `Task`
model, watching out for items you DON'T want searchable (for
example, `encrypted_password`, `password_reset_token`, `owner` or
other sensitive information). You can use the following as a base:

```ruby
class Task < ApplicationRecord

  # ...

  def self.ransackable_attributes(auth_object = nil)
    ["assignee_id", "author_id", "created_at", "description", "expired_at", "id", "name", "state", "updated_at"]
  end

  # ...

end
```

    app/controllers/api/v1/tasks_controller.rb:6:in `index'
    test/controllers/api/v1/tasks_controller_test.rb:12:in `block in <class:TasksControllerTest>'

2023-04-25 07:40 UTC, krav-ets commented
> таких коммитов быть не должно, если нужен код из девелопа в фича ветке, надо делать ребейс фича ветки от девелопа

В данном случае лучше будет пересоздать ветку и сделать все правильно, да?

2023-04-25 15:11 UTC, greybutton commented
не, ребейс сделай как написал и мердж коммит исчезнет

2023-04-25 15:15 UTC, greybutton commented on app/models/task.rb
> +  def self.ransackable_attributes(_auth_object = nil)
что то новенькое. можешь поставить последнюю третью версию рансака и убрать этот код, либо оставить четвертую версию и этот код как есть

2023-04-25 15:26 UTC, greybutton commented on app/models/task.rb
> +  def self.ransackable_attributes(_auth_object = nil)
вот так еще можешь сделать, чтобы все поля не перечислять

```
  def ransackable_attributes(auth_object = nil)
    column_names + _ransackers.keys
  end
```

2023-05-05 15:50 UTC, YJorge commented
количество

> > [Merge branch 'develop' into feature/api](https://github.com/krav-ets/db-project/pull/14/commits/b151e6d94070e87e26450403f019a857eff2cc73)
> 
> таких коммитов быть не должно, если нужен код из девелопа в фича ветке, надо делать ребейс фича ветки от девелопа

количество комитов, не относящихся к этой задаче, стало еще больше. Убрать их поможет интерактивный rebase - `git rebase -i`

2023-05-08 12:29 UTC, krav-ets commented
я правильно понимаю, что нужно будет сделать` git rebase -i HEAD~20`
и удалить коммит **[Merge branch 'develop' into feature/api](https://github.com/krav-ets/db-project/pull/14/commits/b151e6d94070e87e26450403f019a857eff2cc73)**, а также все дублирующиеся коммиты от 26го апреля?

2023-06-22 14:28 UTC, merged